### PR TITLE
Re-added ability to define environment variables inside the NRM pod b…

### PR DESCRIPTION
**Pull request by l0wl3vel**
…y referencing a secret

### CODE REVIEW

**Comment by CMYanko** [comment]
Do tis require matching value in the values.yml?

**Comment by l0wl3vel** [comment]
Using this key would look something like this:
```
nexus:
  envFrom:
    - secretRef:
       name: secret
```

**Comment by CMYanko** [comment]
Do we need some conditional logic in the template not to render this unless there are values? Or is there a benign default we can put in the values, right now the chart will fail lintiing

**Comment by l0wl3vel** [comment]
I see what you mean now. I tested that today and if you do not define envFrom: it doesn't do anything and does not appear in the final deployment on the cluster.

**Comment by CMYanko** [comment]
Ok, I'll do a quick lint and dry run to confirm

**Pull request merged**
