### PR TITLE
NEXUS-34871 - Resiliency Helm charts 41.1.3

### PR DESCRIPTION
**Pull request by bobotimi**
#### Description of Change
Publish 41.1.3 version of nexus-repository-manager and nxrm-aws-resiliency

### CODE REVIEW

**Review by jflinchbaugh — APPROVED** [review]
+1 i'll merge this.

**Comment by bobotimi** [comment]
Thanks @jflinchbaugh

**Comment by hajimeo** [comment]
so we no longer uses https://github.com/sonatype/nxrm3-helm-repository/ for NXRM3 resiliency?

**Comment by bobotimi** [comment]
> @bobotimi , so we no longer uses https://github.com/sonatype/nxrm3-helm-repository/ for NXRM3 resiliency?

@hajimeo  The NXRM3 resiliency charts still live in the https://github.com/sonatype/nxrm3-helm-repository/ git repository.

What this PR is doing is to publish the helm index. We publish the helm index from this repository's docs directory. Publishing the helm index this way (i.e. via this PR) is a temporary solution until we finish the automation.

**Pull request merged**
