### PR TITLE
Add enabled value to deployment in chart

### PR DESCRIPTION
**Pull request by yuvalman**
Add the ability to disable nexus deployment.

### CODE REVIEW

**Comment by ruckc** [comment]
Why would you want to disable deployment of the only pod in a helm chart?

**Comment by yuvalman** [comment]
I can think of two main reasons for disabling the deployment:

1. It can act as a "Feature Toggle" (An easy option to remove/add the functionality of a helm chart in your cluster). Today, In the Nexus helm chart, the only template that doesn't support the option to be enabled/disabled is the deployment.

2. Costs - It gives you the option to customize different properties for different clusters you are using in your product.
For example, as part of your CI/CD, you would like to deploy the chart only on production clusters and disable it to all your dev clusters (For saving costs).

**Comment by ruckc** [comment]
I look at it then as just don't deploy that helm chart entirely if you don't want the deployment.

**Comment by yuvalman** [comment]
In that case, how would you remove and add the helm chart easily when needed, without deleting the whole chart and deploy it back?

I'm talking about use cases that you extend the chart with your own Kubernetes objects (For configuring the chart to your own requirements). In that use case, we can not add those objects using "Feature Toggle" because the deployment of the nexus chart will always be deployed.

It's a useful feature that can serve such use cases.

We can also change the logic of the enabled flag to be for all the deployment instead of only change the number of replicas:


`  
{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
.
.
.
.
{{- end }}
`

**Pull request closed without merging**
