### PR TITLE
Added the logic for changing ingress definition for K8s 1.22+, while …

### PR DESCRIPTION
**Pull request by jeroenlandheer**
…preserving the older definitions for older Kubernetes versions.

See Issue #74

### CODE REVIEW

**Comment by jeroenlandheer** [comment]
I also added some fixes to the NOTES.txt, these dumped a massive amount of numbers after installing with ingress enabled.

**Comment by jrpedrianes** [comment]
Any news on this?

**Comment by DaviGia** [comment]
@jeroenlandheer Thanks, for the PR. I tried your code and I've found a couple of problems with your changes. If you try to dry-run with the following values you should see a nil pointer exception:

``` yaml
nexus:
  docker:
    enabled: true
    registries:
     - host: docker-proxy.test.local
       port: 5000
     - host: docker-hosted.test.local
       port: 5001

ingress:
  enabled: true
  className: nginx
  hostPath: /
  hostRepo: nexus.test.local
```

The problem is that `ingress.yaml` file creates a new yaml section for each docker repository specified in `.Values.nexus.docker.repositories`. This means that in the subsequent sections the context changes. To fix this problem use `$` global variable to force access to root context.

**Comment by jeroenlandheer** [comment]
@DaviGia 
Sorry for the late reply, I've been ill for little over a week. 
I'll take a look later today and will post an update.

**Comment by jeroenlandheer** [comment]
@DaviGia As promised, I've uploaded a fix.

**Comment by DaviGia** [comment]
> @DaviGia As promised, I've uploaded a fix.

Great! The problem now is that no one is accepting this PR.

**Comment by jeroenlandheer** [comment]
@DaviGia 

I've dropped a message in their gitter chat to attract some attention. Maybe that helps, we'll see :)
(I've also signed the Sonatype CLA, so that shouldn't be an issue.)

**Comment by krmichelos** [comment]
@jflinchbaugh Any chance of getting this looked at and released?

**Comment by jflinchbaugh** [comment]
> @jflinchbaugh Any chance of getting this looked at and released?

We've finally updated to the stable v1 Ingress without conditions to downgrade to the v1beta1, since it's been available for so long, so we may not need as much of this PR. Please rebase your PR on the latest, and see if there are still changes you'd like applied. Thanks for your patience.

We've published the latest version of the charts today.

**Comment by jflinchbaugh** [comment]
> @jflinchbaugh I may not be looking at the correct revisions, but it looks like the ability to set the ingressClassName is still a need.

I see.  I had preserved the annotation for ingress.class instead of the `ingressClassName`. `ingressClassName` would be better. I'll see about getting that updated. https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress

**Comment by krmichel** [comment]
@jflinchbaugh Looks like you made the change for ingressClasssName.  Do you have an ETA on when a version of the chart containing that fix might be released?

**Comment by jflinchbaugh** [comment]
> @jflinchbaugh Looks like you made the change for ingressClasssName. Do you have an ETA on when a version of the chart containing that fix might be released?

It's been released. https://artifacthub.io/packages/search?org=sonatype

**Pull request closed without merging**
