### PR TITLE
Kubernetes 1.22 support

### PR DESCRIPTION
**Pull request by Jonomir**
move ingresses from removed `networking.k8s.io/v1beta1` api to `networking.k8s.io/v1` 
solves https://github.com/sonatype/helm3-charts/issues/74

### CODE REVIEW

**Comment by ruckc** [comment]
this needs to be version checked depending on the cluster version, to use either v1beta1, v1beta2, or v1 APIs

**Comment by Jonomir** [comment]
I split it up into two templates
`ingress.yaml` for `v1` and `ingress-deprecated.yaml` for `v1beta1`
Both check for the availability of the used api.

I added the ingress.className value, because in `v1` it is not an annotation anymore.
The `ingress-deprecated.yaml` automatically adds it as an annotation.

**Comment by jeroenlandheer** [comment]
@Jonomir It seems we've been working on the same issue, see my PR, it already has that feature and some additional fixes.

**Comment by jflinchbaugh** [comment]
kubernetes 1.22 has been added.

**Pull request closed without merging**
